version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip3 install kafka  -t lib
      - pip3 install pymysql -t lib
      - pip3 install request  -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip Avalanche_getAvaScanInfo_sendonKafka.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name avalanche  --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
